favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9702128
  brandStrength: 1
  lightness: 0.0106383
  brandColors:
    - '#323236'
    - '#86B4DA'
    - '#EAD7CF'
    - '#040406'
    - '#4A6D8A'
  rhythmicContrast: 0.4425532
typography_spectrum: 0.506383
layout_spectrum: 0.9531915
analytics:
  twitter: null
  google: null
  facebook: null
name: FriedArt
